### ISSUE TITLE
RuntimeError: CUDA error: out of memory when I run vanilla_segmentation "train..py"

### ISSUE THREAD

**Issue by yjdfly** [j96w/DenseFusion#104]
When I run “vanilla_segmentation/train.py” directly, an error occurs “RuntimeError: CUDA error: out of memory”. So I reduced the value of batch size to 2 or 1, and I used "with torch.no_grad():" , and then the other error occurred. Can anyone tell me why? Thank U.

robot@robot:~/DenseFusion-master/vanilla_segmentation$ python train.py
5000 1000
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
2019-10-27 12:19:42,902 : Train time 00h 00m 00s, Training started
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    semantic = model(rgb)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/robot/DenseFusion-master/vanilla_segmentation/segnet.py", line 118, in forward
    x12d = F.relu(self.bn12d(self.conv12d(x1d)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 643, in relu
    return torch.relu(input)
RuntimeError: CUDA error: out of memory

robot@robot:~/DenseFusion-master/vanilla_segmentation$ python train.py
5000 1000
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
2019-10-27 12:46:55,674 : Train time 00h 00m 00s, Training started
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    semantic_loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by j96w** [comment]
Hi, how about lower the batch size if GPU memory is not enough?

**Comment by yjdfly** [comment]
when I lower the batch size from 3 to1 and use "with torch.no_grad():" before "...=model(rgb)"，the error"CUDA out of memory" is solved，but the other error "element 0 of tenseor ..."appears at "....forward"，detailed errors are posted at the top.I can't solve it ,hope you can tell me why.Thanks a lot.

**Comment by huckl3b3rry87** [comment]
I ran with 8 12 GB GPUS and got this error

**Comment by huckl3b3rry87** [comment]
My problem was that I was running int docker image and by setting ``--ipc=host`` in the run script, I fixed the issue
