### ISSUE TITLE
make with conda 2 (python 2) ; doesn't work 

### ISSUE THREAD

**Issue by hamza-04** [j96w/DenseFusion#17]
hi @j96w , i'm working on conda 2.7 , so i built the knn_torch with python 2 in conda environment and always get this problem with modules ,

    set -e
    export PYTHONUNBUFFERED=True
    PYTHONUNBUFFERED=True
    export CUDA_VISIBLE_DEVICES=0
    CUDA_VISIBLE_DEVICES=0
    python ./tools/train.py --dataset linemod --dataset_root ./datasets/linemod/Linemod_preprocessed
    Traceback (most recent call last):
    File "./tools/train.py", line 12, in
    import numpy as np
    ImportError: No module named numpy

this is the make by python2 : 
..$ make
python2 build_ffi.py
generating /tmp/tmpmsC9ic/_knn_pytorch.c
setting the current directory to '/tmp/tmpmsC9ic'
running build_ext
building '_knn_pytorch' extension
creating home
creating home/hamza
creating home/hamza/Téléchargements
creating home/hamza/Téléchargements/DenseFusion-master
creating home/hamza/Téléchargements/DenseFusion-master/lib
creating home/hamza/Téléchargements/DenseFusion-master/lib/knn
creating home/hamza/Téléchargements/DenseFusion-master/lib/knn/src
gcc -pthread -B /home/hamza/anaconda2/envs/py27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hamza/anaconda2/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/hamza/anaconda2/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hamza/anaconda2/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/hamza/Téléchargements/DenseFusion-master/lib/knn/include -I/home/hamza/anaconda2/envs/py27/include/python2.7 -c _knn_pytorch.c -o ./_knn_pytorch.o -std=c99
gcc -pthread -B /home/hamza/anaconda2/envs/py27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hamza/anaconda2/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/hamza/anaconda2/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/hamza/anaconda2/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/hamza/Téléchargements/DenseFusion-master/lib/knn/include -I/home/hamza/anaconda2/envs/py27/include/python2.7 -c /home/hamza/Téléchargements/DenseFusion-master/lib/knn/src/knn_pytorch.c -o ./home/hamza/Téléchargements/DenseFusion-master/lib/knn/src/knn_pytorch.o -std=c99
gcc -pthread -shared -B /home/hamza/anaconda2/envs/py27/compiler_compat -L/home/hamza/anaconda2/envs/py27/lib -Wl,-rpath=/home/hamza/anaconda2/envs/py27/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_knn_pytorch.o ./home/hamza/Téléchargements/DenseFusion-master/lib/knn/src/knn_pytorch.o /home/hamza/Téléchargements/DenseFusion-master/lib/knn/build/knn_cuda_kernel.so /usr/local/cuda/lib64/libnppitc_static.a /usr/local/cuda/lib64/libcublas_device.a /usr/local/cuda/lib64/libnppc_static.a /usr/local/cuda/lib64/libcusparse_static.a /usr/local/cuda/lib64/libcublas_static.a /usr/local/cuda/lib64/libcufftw_static.a /usr/local/cuda/lib64/libnppicom_static.a /usr/local/cuda/lib64/libnppicc_static.a /usr/local/cuda/lib64/libcufft_static.a /usr/local/cuda/lib64/libcudnn_static.a /usr/local/cuda/lib64/libnppist_static.a /usr/local/cuda/lib64/libcurand_static.a /usr/local/cuda/lib64/libnpps_static.a /usr/local/cuda/lib64/libnppig_static.a /usr/local/cuda/lib64/libcudadevrt.a /usr/local/cuda/lib64/libnppidei_static.a /usr/local/cuda/lib64/libnppisu_static.a /usr/local/cuda/lib64/libnvgraph_static.a /usr/local/cuda/lib64/libcusolver_static.a /usr/local/cuda/lib64/libnppif_static.a /usr/local/cuda/lib64/libnppim_static.a /usr/local/cuda/lib64/libculibos.a /usr/local/cuda/lib64/libcudart_static.a /usr/local/cuda/lib64/libnppial_static.a -L/home/hamza/anaconda2/envs/py27/lib -lpython2.7 -o ./_knn_pytorch.so

I'm working with linemod data

i tried it also outside conda environment , always the same problem . i don't know if i miss something !
thank you in advance

**Comment by j96w** [comment]
Hi, could you double check whether your numpy is installed correctly?

**Comment by hamza-04** [comment]
Hi , thank you , it worked for me finally , xhen i type : PYTHON=python2 sh train_linemod.sh he knows the right version . 

Actually now i got an other problem which is : can't import from datasets.linemod.dataset thhe function   PoseDataset ..   I added all data , i checked the path and every but always the same problem . 

I'm only trying to train on linemod data  ( i commented ycb_data) 

Thank you in advance

**Comment by j96w** [comment]
My suggestion might be to check the path again, especially the root dir where you start running the program.

**Comment by huckl3b3rry87** [comment]
using python3 with ros is not fun, so I am trying to use python2, but I run into this issue
```
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
0.4.1
>>> from torch.utils.ffi import create_extension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 14, in <module>
    raise ImportError("torch.utils.ffi requires the cffi package")
ImportError: torch.utils.ffi requires the cffi package
```

@j96w any thoughts?

**Comment by huckl3b3rry87** [comment]
as the error say....this fixed it
```
 pip install cffi
```
